author:
  name: "Faith Mwende Muli"
  links:
    - title: "GitHub"
      url: "https://github.com/faiyanmwesh"
    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/faith-mwende-muli-89a81223a/"
