title: "Faith Mwende Muli"
email: "faiyanmwesh2018@gmail.com"
description: "Aspiring Data Analyst | Python • Power BI • Tableau"
url: "https://faiyanmwesh.github.io"
theme: minima

author:
  name: "Faith Mwende Muli"
  links:
    - label: "GitHub"
      url: "https://github.com/faiyanmwesh"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/faith-mwende-muli-89a81223a/"
